# Generated by Django 6.0.5 on 2026-07-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='America/Bogota', max_length=64),
        ),
    ]
