# Generated by Django 6.0.5 on 2026-07-12 18:43

import core.models.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_version_guard_trigger'),
        ('orgs', '0001_initial'),
        ('projects', '0002_projectconfigversion_checklist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('done', 'Done'), ('failed', 'Failed')], default='done', max_length=8)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('config_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='projects.projectconfigversion')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_runs', to='documents.documentversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=core.models.mixins.uuid7, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('items', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='orgs.organization')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='uniq_template_name')],
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=200)),
                ('outcome', models.CharField(choices=[('pass', 'Pass'), ('warn', 'Warn'), ('fail', 'Fail')], max_length=4)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('message', models.CharField(blank=True, default='', max_length=300)),
                ('check_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='checks.checkrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('check_run', 'key'), name='uniq_result_per_check')],
            },
        ),
    ]
