# Generated by Django 6.0.5 on 2026-07-22 20:00

import core.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=core.models.mixins.uuid7, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=32)),
                ('file_a_name', models.CharField(default='', max_length=255)),
                ('file_b_name', models.CharField(default='', max_length=255)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'expires_at'], name='public_tool_status_28f4db_idx')],
            },
        ),
    ]
