# Generated by Django 6.0.5 on 2026-07-22 20:00

import core.models.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0003_organization_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=core.models.mixins.uuid7, editable=False, unique=True)),
                ('plan_key', models.CharField(default='pro', max_length=20)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('expired', 'Expired')], default='trialing', max_length=10)),
                ('trial_ends_at', models.DateTimeField()),
                ('trial_ending_notified_at', models.DateTimeField(blank=True, null=True)),
                ('trial_expired_notified_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='orgs.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
