# Generated by Django 6.0.5 on 2026-07-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectconfigversion',
            name='checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectconfigversion',
            name='section_owners',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
