# Generated by Django 6.0.5 on 2026-08-03 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_remove_invitation_uniq_pending_invitation_per_email_and_more'),
        ('projects', '0002_projectconfigversion_checklist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='uniq_project_slug_alive',
        ),
        migrations.AddField(
            model_name='project',
            name='slug_alive',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(deleted_at__isnull=True, then=models.F('slug')), default=models.Value(None), output_field=models.SlugField(max_length=160)), output_field=models.SlugField(max_length=160)),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('organization', 'slug_alive'), name='uniq_project_slug_alive'),
        ),
    ]
