# Generated by Django 6.0.5 on 2026-07-12 14:36

import core.models.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=core.models.mixins.uuid7, editable=False, unique=True)),
                ('job_type', models.CharField(choices=[('analysis', 'Analysis'), ('comparison', 'Comparison'), ('seal_review', 'Seal review (D5)'), ('reanchor', 'Re-anchor observations'), ('check_run', 'Check run'), ('sample_project', 'Sample project seed (A1)')], max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=100)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engine_jobs', to='documents.documentversion')),
            ],
            options={
                'indexes': [models.Index(fields=['job_type', 'status'], name='engine_engi_job_typ_0aac07_idx')],
            },
        ),
    ]
