# Generated by Django 6.0.5 on 2026-08-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginejob',
            name='idempotency_key',
            field=models.CharField(db_collation='utf8mb4_bin', max_length=200, unique=True),
        ),
    ]
