# Generated by Django 6.0.5 on 2026-07-12 18:02

import core.models.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_version_guard_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=core.models.mixins.uuid7, editable=False, unique=True)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('resolved', 'Resolved')], default='open', max_length=8)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to=settings.AUTH_USER_MODEL)),
                ('created_on_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations_created', to='documents.documentversion')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='documents.document')),
                ('resolved_in_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentversion')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='documents.section')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObservationReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=core.models.mixins.uuid7, editable=False, unique=True)),
                ('body', models.TextField()),
                ('status_change', models.CharField(blank=True, default='', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='observations.observation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObservationAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.PositiveIntegerField(default=1)),
                ('quads', models.JSONField(blank=True, default=list)),
                ('text_snippet', models.CharField(blank=True, default='', max_length=300)),
                ('method', models.CharField(choices=[('exact', 'Exact (section intact)'), ('reanchored_section', 'Re-anchored to the section'), ('orphaned', 'Orphaned (section gone)')], max_length=20)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_anchors', to='documents.documentversion')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchors', to='observations.observation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('observation', 'document_version'), name='uniq_anchor_per_version')],
            },
        ),
    ]
