# Generated by Django 6.0.5 on 2026-07-12 17:17

import core.models.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comparisons', '0001_initial'),
        ('documents', '0002_version_guard_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=core.models.mixins.uuid7, editable=False, unique=True)),
                ('covers_all', models.BooleanField(default=False)),
                ('signed_payload', models.JSONField()),
                ('signature', models.TextField()),
                ('key_id', models.CharField(max_length=40)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seals', to='documents.documentversion')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SealSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_hash', models.CharField(max_length=64)),
                ('seal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_sections', to='reviews.seal')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='documents.section')),
            ],
        ),
        migrations.CreateModel(
            name='SealValidityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('preserved', 'Preserved (with certificate)'), ('invalidated', 'Invalidated (requires re-review)'), ('pending_confirmation', 'Pending coordinator confirmation'), ('superseded', 'Superseded by a newer version')], max_length=20)),
                ('proposed_decision', models.CharField(blank=True, choices=[('preserved', 'Preserved (with certificate)'), ('invalidated', 'Invalidated (requires re-review)'), ('pending_confirmation', 'Pending coordinator confirmation'), ('superseded', 'Superseded by a newer version')], default='', max_length=20)),
                ('reason_code', models.CharField(blank=True, default='', max_length=40)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('decided_mode', models.CharField(choices=[('auto', 'Automatic'), ('coordinator', 'Coordinator')], default='auto', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('comparison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comparisons.comparison')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('seal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validity_records', to='reviews.seal')),
                ('to_document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seal_validity_records', to='documents.documentversion')),
            ],
            options={
                'ordering': ['to_document_version__number'],
            },
        ),
        migrations.AddConstraint(
            model_name='seal',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('document_version', 'reviewer'), name='uniq_active_seal_per_reviewer'),
        ),
        migrations.AddConstraint(
            model_name='sealsection',
            constraint=models.UniqueConstraint(fields=('seal', 'section'), name='uniq_seal_section'),
        ),
        migrations.AddConstraint(
            model_name='sealvalidityrecord',
            constraint=models.UniqueConstraint(fields=('seal', 'to_document_version'), name='uniq_validity_per_version'),
        ),
    ]
