# Generated by Django 6.0.5 on 2026-07-12 17:54

import core.models.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_version_guard_trigger'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=core.models.mixins.uuid7, editable=False, unique=True)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('superseded', 'Superseded by a newer version')], default='open', max_length=10)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='documents.documentversion')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=8)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to=settings.AUTH_USER_MODEL)),
                ('review_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='reviews.reviewrequest')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reviewrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('document_version',), name='uniq_open_request_per_version'),
        ),
        migrations.AddConstraint(
            model_name='reviewassignment',
            constraint=models.UniqueConstraint(fields=('review_request', 'reviewer'), name='uniq_assignment_per_reviewer'),
        ),
    ]
