# Generated by Django 6.0.5 on 2026-07-12 20:51

import core.models.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_spanish_unaccent_fts'),
        ('orgs', '0003_organization_plan'),
        ('reviews', '0002_reviewrequest_reviewassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=core.models.mixins.uuid7, editable=False, unique=True)),
                ('serial', models.CharField(max_length=40)),
                ('snapshot', models.JSONField()),
                ('pdf_key', models.CharField(max_length=500)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='documents.documentversion')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='orgs.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'serial'), name='uniq_serial_per_org')],
            },
        ),
    ]
