# Generated by Django 6.0.5 on 2026-08-03 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_document_uniq_document_slug_alive_and_more'),
        ('reviews', '0003_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reviewrequest',
            name='uniq_open_request_per_version',
        ),
        migrations.RemoveConstraint(
            model_name='seal',
            name='uniq_active_seal_per_reviewer',
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='document_version_open',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(status='open', then=models.F('document_version')), default=models.Value(None), output_field=models.BigIntegerField()), output_field=models.BigIntegerField()),
        ),
        migrations.AddField(
            model_name='seal',
            name='document_version_active',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(revoked_at__isnull=True, then=models.F('document_version')), default=models.Value(None), output_field=models.BigIntegerField()), output_field=models.BigIntegerField()),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='pdf_key',
            field=models.CharField(db_collation='utf8mb4_bin', max_length=500),
        ),
        migrations.AlterField(
            model_name='seal',
            name='key_id',
            field=models.CharField(db_collation='utf8mb4_bin', max_length=40),
        ),
        migrations.AlterField(
            model_name='seal',
            name='signature',
            field=models.TextField(db_collation='utf8mb4_bin'),
        ),
        migrations.AlterField(
            model_name='sealsection',
            name='body_hash',
            field=models.CharField(db_collation='utf8mb4_bin', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='reviewrequest',
            constraint=models.UniqueConstraint(fields=('document_version_open',), name='uniq_open_request_per_version'),
        ),
        migrations.AddConstraint(
            model_name='seal',
            constraint=models.UniqueConstraint(fields=('document_version_active', 'reviewer'), name='uniq_active_seal_per_reviewer'),
        ),
    ]
