# Generated by Django 6.0.5 on 2026-08-03 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_organization_plan'),
        ('projects', '0002_projectconfigversion_checklist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invitation',
            name='uniq_pending_invitation_per_email',
        ),
        migrations.AddField(
            model_name='invitation',
            name='email_pending',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(status='pending', then=models.F('email')), default=models.Value(None), output_field=models.EmailField(max_length=254)), output_field=models.EmailField(max_length=254)),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(db_collation='utf8mb4_bin', max_length=64, unique=True),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('project', 'email_pending'), name='uniq_pending_invitation_per_email'),
        ),
    ]
