# Generated by Django 6.0.5 on 2026-07-12 16:33

import core.models.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_version_guard_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=core.models.mixins.uuid7, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('trigger', models.CharField(choices=[('auto', 'Automatic (post-upload)'), ('manual', 'Manual (E1)')], default='manual', max_length=8)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='documents.document')),
                ('from_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_from', to='documents.documentversion')),
                ('to_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_to', to='documents.documentversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stable_key', models.CharField(max_length=250)),
                ('heading_from', models.CharField(blank=True, default='', max_length=300)),
                ('heading_to', models.CharField(blank=True, default='', max_length=300)),
                ('change_type', models.CharField(choices=[('unchanged', 'Unchanged'), ('modified', 'Modified'), ('added', 'Added'), ('removed', 'Removed'), ('renamed_only', 'Renamed only')], max_length=13)),
                ('similarity', models.FloatField(blank=True, null=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('word_diff', models.JSONField(blank=True, default=list)),
                ('bboxes_from', models.JSONField(blank=True, default=list)),
                ('bboxes_to', models.JSONField(blank=True, default=list)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffs', to='comparisons.comparison')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='documents.section')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.AddConstraint(
            model_name='comparison',
            constraint=models.UniqueConstraint(fields=('from_version', 'to_version'), name='uniq_comparison_pair'),
        ),
    ]
