# Generated by Django 6.0.5 on 2026-07-12 20:52

import core.models.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0001_initial'),
        ('projects', '0002_projectconfigversion_checklist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=core.models.mixins.uuid7, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_as', to='comparisons.comparison')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_comparisons', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='uniq_saved_comparison_name')],
            },
        ),
    ]
