# Generated by Django 6.0.5 on 2026-07-12 14:36

import core.models.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=core.models.mixins.uuid7, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('latest_number', models.PositiveIntegerField(default=0)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=core.models.mixins.uuid7, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('number', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True, default='')),
                ('sha256', models.CharField(max_length=64)),
                ('file_key', models.CharField(max_length=500)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('source_scenario', models.CharField(choices=[('text_native', 'Native text'), ('scanned_ocr', 'Scanned (OCR)'), ('mixed', 'Mixed')], default='text_native', max_length=12)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('thumb_key', models.CharField(blank=True, default='', max_length=500)),
                ('thumb_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('config_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='projects.projectconfigversion')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='approved_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentversion'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stable_key', models.CharField(max_length=250)),
                ('title_current', models.CharField(max_length=300)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('created_in_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_created', to='documents.documentversion')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='documents.document')),
                ('retired_in_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections_retired', to='documents.documentversion')),
            ],
        ),
        migrations.CreateModel(
            name='SectionLineage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.CharField(choices=[('same', 'Same'), ('renamed', 'Renamed'), ('split_from', 'Split from'), ('merged_into', 'Merged into'), ('added', 'Added'), ('removed', 'Removed')], max_length=12)),
                ('similarity', models.FloatField(blank=True, null=True)),
                ('decided_mode', models.CharField(default='auto', max_length=12)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineage', to='documents.documentversion')),
                ('from_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='documents.section')),
                ('to_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='documents.section')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading_text', models.CharField(max_length=300)),
                ('heading_hash', models.CharField(max_length=64)),
                ('body_hash', models.CharField(max_length=64)),
                ('normalized_text', models.TextField()),
                ('page_start', models.PositiveIntegerField()),
                ('page_end', models.PositiveIntegerField()),
                ('bboxes', models.JSONField(default=list)),
                ('order_index', models.PositiveIntegerField()),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_versions', to='documents.documentversion')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='documents.section')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', 'sha256'], name='documents_d_documen_2af20c_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'number'), name='uniq_version_number'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'slug'), name='uniq_document_slug_alive'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('document', 'stable_key'), name='uniq_section_key'),
        ),
        migrations.AddConstraint(
            model_name='sectionversion',
            constraint=models.UniqueConstraint(fields=('section', 'document_version'), name='uniq_section_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='sectionversion',
            constraint=models.UniqueConstraint(fields=('document_version', 'order_index'), name='uniq_snapshot_order'),
        ),
    ]
