# Generated by Django 6.0.5 on 2026-07-12 18:50

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_version_guard_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionversion',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='sectionversion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='sectionversion_fts_gin'),
        ),
    ]
