# Generated by Django 6.0.5 on 2026-08-03 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_spanish_unaccent_fts'),
        ('projects', '0002_projectconfigversion_checklist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='uniq_document_slug_alive',
        ),
        migrations.AddField(
            model_name='document',
            name='slug_alive',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(deleted_at__isnull=True, then=models.F('slug')), default=models.Value(None), output_field=models.SlugField(max_length=220)), output_field=models.SlugField(max_length=220)),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='file_key',
            field=models.CharField(db_collation='utf8mb4_bin', max_length=500),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='sha256',
            field=models.CharField(db_collation='utf8mb4_bin', max_length=64),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='thumb_key',
            field=models.CharField(blank=True, db_collation='utf8mb4_bin', default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='sectionversion',
            name='body_hash',
            field=models.CharField(db_collation='utf8mb4_bin', max_length=64),
        ),
        migrations.AlterField(
            model_name='sectionversion',
            name='heading_hash',
            field=models.CharField(db_collation='utf8mb4_bin', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('project', 'slug_alive'), name='uniq_document_slug_alive'),
        ),
    ]
