# Generated by Django 6.0.5 on 2026-07-12 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_id_ref', models.BigIntegerField(db_index=True)),
                ('project_id_ref', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(db_index=True, max_length=60)),
                ('object_type', models.CharField(blank=True, default='', max_length=40)),
                ('object_id_ref', models.CharField(blank=True, default='', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project_id_ref', 'created_at'], name='audit_audit_project_4ee633_idx'), models.Index(fields=['org_id_ref', 'event_type', 'created_at'], name='audit_audit_org_id__873401_idx')],
            },
        ),
    ]
