# Generated by Django 6.0.5 on 2026-07-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagingPhaseBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('current_phase', models.CharField(choices=[('design', 'Etapa de diseño'), ('development', 'Etapa de desarrollo')], default='design', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('design_duration_days', models.PositiveIntegerField(default=5)),
                ('development_duration_days', models.PositiveIntegerField(default=10)),
                ('contact_whatsapp', models.CharField(default='+57 323 8122373', max_length=20)),
                ('contact_email', models.EmailField(default='team@projectapp.co', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staging Phase Banner',
                'verbose_name_plural': 'Staging Phase Banner',
            },
        ),
    ]
